name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Add Remote
        run: git remote add space https://huggingface.co/spaces/ridaf/sentiment

      - name: Push to Hub
        env:
          HF_TOKEN: ${{ secrets.HG }} # Use HG as your secret
        run: |
          git push --force https://user:$HF_TOKEN@huggingface.co/spaces/ridaf/sentiment main
